[[redirects]]
  from = "https://share-mbktechstudio.netlify.app/*"
  to = "https://share.mbktechstudio.com/:splat"
  status = 301
  force = true 

 [[redirects]]
  from = "https://share.ibnekhalid.me/*"
  to = "https://share.mbktechstudio.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://share.mbktech.xyz/*"
  to = "https://share.mbktechstudio.com/:splat"
  status = 301
  force = true
